### ISSUE TITLE
Doesn't work for Android?

### ISSUE THREAD

**Issue by Lev-Guzeev** [mikefogg/CrittercismModule#1]
Hi, Mike
The module (1.0.1) works like a charm on iOS, but I can't make it work for Android 4.0+ (tried both emulator and device). Tried to crash the app with .crash method and by setting invalid type name in ListView template (it crashes iOS application and crashlog is there on app.crittercism.com), but that didn't result in crashlogs.
Here's my simple code:
appId = Ti.UI.iOS ? IOS_APP_ID : ANDROID_APP_ID
module = require('crittercism');
module.start({
        appID: appId,
        setLogcatReportingEnabled: true
});
module.crash('Test android crash');
Also tried with setLogcatReportingEnabled = false, but same effect - app loads are registered, but crash - not. 
Do I do something wrong?

**Comment by mikefogg** [comment]
@Lev-Guzeev, ah sorry you're having problems with it! Lets see if we can figure it out. The force crash method is hit or miss in Android, sometimes it literally just won't crash the app no matter what I did on various devices. Have you tried sending a handledException just to see if it's communicating with Crittercism at all? Something like:

```
module.logHandledException({
  name: "SAMPLE EXCEPTION",
  reason: "Testing an exception"
});
```

**Comment by Lev-Guzeev** [comment]
Android app communicates with Crittercism, because it registers app loads and performance statistics. 
Another issue is that performance statistics is empty for iOS

**Comment by Lev-Guzeev** [comment]
Hey, just got a real crash and it was logged!
Will create another issue for performance statistics on iOS.

**Comment by mikefogg** [comment]
@Lev-Guzeev, awesome! Phew :)
