### ISSUE TITLE
Do I have to start crittercism in all windows??

### ISSUE THREAD

**Issue by hardikamal** [mikefogg/CrittercismModule#7]
var Crittercism = require('crittercism'); // Initialize the SquareCamera module
var app_id = "xxxxxxxxxxxxxxxxx";
if(Ti.Platform.osname == 'android'){
  app_id = "xxxxxxxxxxxxxxxxxx";
};
Crittercism.start({
  appID: app_id,
  customAppVersion: "testing_version_1", // Optional (Available on Android Only - Will be ignored on iOS)
  setLogcatReportingEnabled: true // Optional (Available on Android Only - Will be ignored on iOS)
});

Do i have to write this code in all the windows(screens) or is it possible to write only in alloy.js file??

Thanks

**Comment by mikefogg** [comment]
hey @hardikamal! Nope, you don't have to do this in every page. This should just be done once. Personally, I do it in app.js before opening my main window :)

**Comment by hardikamal** [comment]
solved...!!!
